# Generated by Django 4.1.5 on 2023-01-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('emri', models.CharField(max_length=25)),
                ('mbiemri', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lajmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
                ('pershkrimi', models.CharField(max_length=200)),
                ('permbajtja', models.TextField(max_length=500)),
                ('foto', models.ImageField(upload_to='')),
                ('data', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('autori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flash.autori')),
                ('kategoria', models.ManyToManyField(to='flash.kategoria')),
            ],
        ),
    ]
