# Generated by Django 4.1.5 on 2023-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lajmi',
            name='foto',
            field=models.ImageField(upload_to='flash'),
        ),
    ]
