# Generated by Django 4.1.5 on 2023-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_alter_autori_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lajmi',
            name='foto',
            field=models.ImageField(null=True, upload_to='flash'),
        ),
        migrations.AlterField(
            model_name='lajmi',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
